[package]
name = "gruglb"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
rand = "0.8.5"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
serde_yaml = "0.9.25"
thiserror = "1.0.49"
